name: 'Install Qt5 arm64'
description: 'Install Qt on your Github Actions workflows with just one simple action'
inputs:
  version:
    description: 'Version of Qt5 to install'
    default: '5.15.2'
runs:
  using: "composite"
  steps:
    - run: |
        function build_qt5_arch()
        {
            local arch=$1
            local _target_mkspec_name="macx-clang-$1"
            if ! [[ -d "${{ env.GITHUB_WORKSPACE }}/qt5/qtbase/mkspecs/${_target_mkspec_name}" ]]
            then
                cp -r "${{ env.GITHUB_WORKSPACE }}/qt5/qtbase/mkspecs/macx-clang" "${{ env.GITHUB_WORKSPACE }}/qt5/qtbase/mkspecs/${_target_mkspec_name}"
                target_macx_conf_file="${{ env.GITHUB_WORKSPACE }}/qt5/qtbase/mkspecs/${_target_mkspec_name}/qmake.conf"
                sed -i '' -e '$ d' "${target_macx_conf_file}"
                echo "QMAKE_APPLE_DEVICE_ARCHS = $1" >> "${target_macx_conf_file}"
                echo "" >> "${target_macx_conf_file}"
                echo "load(qt_config)" >> "${target_macx_conf_file}"
            fi
            local _qt_cross_compile_args="-xplatform ${_target_mkspec_name}"

            mkdir -p lib-$1 && cd lib-$1
            "${{ env.GITHUB_WORKSPACE }}/qt5/configure" -prefix ${{ env.GITHUB_WORKSPACE }}/lib_$1 -opensource -confirm-license -release -static -appstore-compliant -c++std c++17 -no-pch -I "${{ env.openssl_root }}/include" -L "${{ env.openssl_root }}/lib" -make libs -no-compile-examples -no-dbus -no-icu -qt-pcre -system-zlib -ssl -openssl-linked -no-cups -qt-libpng -qt-libjpeg -no-feature-testlib -no-feature-concurrent -platform macx-clang ${_qt_cross_compile_args}
            make -j$(sysctl -n hw.ncpu)
            make install
            cd -
        }
        curl -L https://gist.githubusercontent.com/R0GERIUS/a2d62e21995e732b9fe510efce71965d/raw/26e9f02b88d6eb41b3a6b636248d6290094ecdc9/qt5_xcode13.patch -o ${{ env.GITHUB_WORKSPACE }}/qt5_xcode13.patch
        git clone https://code.qt.io/qt/qt5.git
        cd qt5
        git checkout "${{ inputs.version }}."
        perl init-repository --module-subset=qtbase,qtmacextras,qtsvg,qttools,qttranslations
        git apply --whitespace=nowarn ${{ env.GITHUB_WORKSPACE }}/qt5_xcode13.patch
        cd -
        build_qt5_arch arm64
      shell: bash
    - id: Prepare build artifacts
      run: |
        mkdir upload
        mv ${{ env.GITHUB_WORKSPACE }}/lib_arm64 upload
      shell: bash
    - id: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Qt-CI_macOS_${{ inputs.version }}_arm64
        path: upload
    