name: 'Install Qt5 arm64'
description: 'Install Qt on your Github Actions workflows with just one simple action'
inputs:
  version:
    description: 'Version of Qt5 to install'
    default: '5.15.2'
  openssl_ver:
    description: 'Version of openssl to install'
    default: '1.1.1m'
  token:
    description: 'Github token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install OpenSSL-Universal
      run: |
        function build_openssl_arch()
        {
            local arch=$1

            mkdir -p lib-$1 && cd lib-$1
            "$GITHUB_WORKSPACE/openssl-${{ inputs.openssl_ver }}/Configure" no-comp no-deprecated no-dynamic-engine no-tests no-shared no-zlib --openssldir=/etc/ssl --prefix=$GITHUB_WORKSPACE/openssl-${{ inputs.openssl_ver }}/lib-$1 -mmacosx-version-min=10.15 darwin64-${arch}-cc
            make -j$(sysctl -n hw.ncpu)
            make install_sw
            cd -
        }
        curl -L https://www.openssl.org/source/openssl-${{ inputs.openssl_ver }}.tar.gz | tar xz
        build_openssl_arch arm64
        build_openssl_arch x86_64
        
        mkdir -p "$GITHUB_WORKSPACE/openssl-${{ inputs.openssl_ver }}-universal/lib"
        cp -r "$GITHUB_WORKSPACE/openssl-${{ inputs.openssl_ver }}/lib-x86_64/include" "$GITHUB_WORKSPACE/openssl-${{ inputs.openssl_ver }}-universal/"
        
        lipo -create "$GITHUB_WORKSPACE/openssl-${{ inputs.openssl_ver }}/lib-x86_64/lib/libcrypto.a" "$GITHUB_WORKSPACE/openssl-${{ inputs.openssl_ver }}/lib-arm64/lib/libcrypto.a" -output "$GITHUB_WORKSPACE/openssl-${{ inputs.openssl_ver }}-universal/lib/libcrypto.a"
        lipo -create "$GITHUB_WORKSPACE/openssl-${{ inputs.openssl_ver }}/lib-x86_64/lib/libssl.a" "$GITHUB_WORKSPACE/openssl-${{ inputs.openssl_ver }}/lib-arm64/lib/libssl.a" -output "$GITHUB_WORKSPACE/openssl-${{ inputs.openssl_ver }}-universal/lib/libssl.a"

        echo "openssl_root=$GITHUB_WORKSPACE/openssl-${{ inputs.openssl_ver }}-universal" >> $GITHUB_ENV
      shell: bash
    - run: |
        function build_qt5_arch()
        {
            local arch=$1
            local _target_mkspec_name="macx-clang-$1"
            if ! [[ -d "$GITHUB_WORKSPACE/qt5/qtbase/mkspecs/${_target_mkspec_name}" ]]
            then
                cp -r "$GITHUB_WORKSPACE/qt5/qtbase/mkspecs/macx-clang" "$GITHUB_WORKSPACE/qt5/qtbase/mkspecs/${_target_mkspec_name}"
                target_macx_conf_file="$GITHUB_WORKSPACE/qt5/qtbase/mkspecs/${_target_mkspec_name}/qmake.conf"
                sed -i '' -e '$ d' "${target_macx_conf_file}"
                echo "QMAKE_APPLE_DEVICE_ARCHS = $1" >> "${target_macx_conf_file}"
                echo "" >> "${target_macx_conf_file}"
                echo "load(qt_config)" >> "${target_macx_conf_file}"
            fi
            local _qt_cross_compile_args="-xplatform ${_target_mkspec_name}"

            mkdir -p lib-$1 && cd lib-$1
            "$GITHUB_WORKSPACE/qt5/configure" -prefix $GITHUB_WORKSPACE/lib_$1 -opensource -confirm-license -release -static -appstore-compliant -c++std c++17 -no-pch -I "${{ env.openssl_root }}/include" -L "${{ env.openssl_root }}/lib" -make libs -no-compile-examples -no-dbus -no-icu -qt-pcre -system-zlib -ssl -openssl-linked -no-cups -qt-libpng -qt-libjpeg -no-feature-testlib -no-feature-concurrent -platform macx-clang ${_qt_cross_compile_args}
            make -j$(sysctl -n hw.ncpu)
            make install
            cd -
        }
        curl -L https://gist.githubusercontent.com/R0GERIUS/a2d62e21995e732b9fe510efce71965d/raw/26e9f02b88d6eb41b3a6b636248d6290094ecdc9/qt5_xcode13.patch -o $GITHUB_WORKSPACE/qt5_xcode13.patch
        git clone https://code.qt.io/qt/qt5.git $GITHUB_WORKSPACE/qt5
        cd $GITHUB_WORKSPACE/qt5
        git checkout "${{ inputs.version }}"
        perl init-repository --module-subset=qtbase,qtmacextras,qtsvg,qttools,qttranslations
        git apply --whitespace=nowarn $GITHUB_WORKSPACE/qt5_xcode13.patch
        cd -
        build_qt5_arch arm64
      shell: bash
    - name: Prepare build artifacts
      run: |
        mkdir upload
        mv $GITHUB_WORKSPACE/lib_arm64 upload
        zip -r upload/lib_arm64.zip upload/lib_arm64
      shell: bash
    - name: Delete Old Release
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Publish GitHub Release
      uses: ncipollo/release-action@v1.8.6
      with:
        prerelease: false
        artifacts: "upload/lib_arm64.zip"
        tag: "latest"
        token: ${{ inputs.token }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Qt-CI_macOS_${{ inputs.version }}_arm64
        path: upload
    